services:
  web:
    image: nginx:alpine
    volumes:
      - ./:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
  php:
    image: php:8.1.8-fpm-alpine3.16
    volumes:
      - ./:/var/www/html